# docker-compose.yml - setup backend for urbalurba
version: '3.9'

services:


  redis:
    image: 'redis:latest'
    container_name: redis
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - urbalurba-network      
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - urbalurba_redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch
    environment:
      - MEILISEARCH_PORT=${MEILISEARCH_PORT}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    ports:
      - '${MEILISEARCH_PORT}:${MEILISEARCH_PORT}'
    networks:
      - urbalurba-network      
    volumes:
      - meilisearch_data:/data.ms


  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - '${NGINX_PORT}:80'
    networks:
      - urbalurba-network      
    volumes:
      - urbalurbafiles:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


volumes:
  urbalurbafiles:
  meilisearch_data:
  redis_data:


networks:
  urbalurba-network:
    external: true