version: '3.9'

services:
  redis:
    image: 'redis:latest'
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - urbalurba-network
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.1
    environment:
      - MEILISEARCH_PORT=${MEILISEARCH_PORT}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    ports:
      - '${MEILISEARCH_PORT}:${MEILISEARCH_PORT}'
    networks:
      - urbalurba-network
    volumes:
      - meilisearch_data:/data.ms

  nginx:
    image: nginx:latest
    environment:
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - '${NGINX_PORT}:80'
    networks:
      - urbalurba-network
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    volumes:
      - urbalurbafiles:/usr/share/nginx/html

volumes:
  urbalurbafiles:
  meilisearch_data:
  redis_data:

networks:
  urbalurba-network:
    external: true

configs:
  redis_conf:
    file: ./redis/redis.conf
  nginx_conf:
    file: ./nginx/nginx.conf
